#!/bin/bash

cd $TRUNK
if [ ! -z  $1 ]
then
    svn st | sed 's/.*persistence\//persistence:/; s/.*webservice\//webservice:/; s/.*bridge\//bridge:/' | grep -v android | grep $1  --color
else
    svn st | sed 's/.*persistence\//persistence:/; s/.*webservice\//webservice:/; s/.*bridge\//bridge:/' | grep -v android
fi
cd -


